version: '3'

services:
  cassandra:
    container_name: cassandra
    image: cassandra:3.11.4
    ports:
      - "9042:9042"   # Native transport
      - "9160:9160"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1 
    volumes:
      - ./data:/var/lib/cassandra 
